// <auto-generated />
using System;
using EcoShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251215083042_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.3.24172.4");

            modelBuilder.Entity("EcoShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Дом и быт"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Красота и уход"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Здоровое питание"
                        });
                });

            modelBuilder.Entity("EcoShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EcoShop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EcoShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "100% биоразлагаемая ручка.",
                            ImageUrl = "data:image/svg+xml;base64,CiAgICAgICAgICAgICAgICA8c3ZnIHdpZHRoPSc2MDAnIGhlaWdodD0nNDAwJyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPgogICAgICAgICAgICAgICAgICAgIDxyZWN0IHdpZHRoPScxMDAlJyBoZWlnaHQ9JzEwMCUnIGZpbGw9JyM4MWM3ODQnLz4KICAgICAgICAgICAgICAgICAgICA8dGV4dCB4PSc1MCUnIHk9JzUwJScgZm9udC1mYW1pbHk9J01vbnRzZXJyYXQsIHNhbnMtc2VyaWYnIGZvbnQtc2l6ZT0nNjAnIGZpbGw9JyNmZmZmZmYnIHRleHQtYW5jaG9yPSdtaWRkbGUnIGRvbWluYW50LWJhc2VsaW5lPSdtaWRkbGUnIGZvbnQtd2VpZ2h0PSdib2xkJz4KICAgICAgICAgICAgICAgICAgICAgICAg0JHQsNC80LHRg9C60L7QstCw0Y8g0YnQtdGC0LrQsAogICAgICAgICAgICAgICAgICAgIDwvdGV4dD4KICAgICAgICAgICAgICAgIDwvc3ZnPg==",
                            Name = "Бамбуковая зубная щетка",
                            Price = 250m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Экономичный и натуральный.",
                            ImageUrl = "data:image/svg+xml;base64,CiAgICAgICAgICAgICAgICA8c3ZnIHdpZHRoPSc2MDAnIGhlaWdodD0nNDAwJyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPgogICAgICAgICAgICAgICAgICAgIDxyZWN0IHdpZHRoPScxMDAlJyBoZWlnaHQ9JzEwMCUnIGZpbGw9JyNiYTY4YzgnLz4KICAgICAgICAgICAgICAgICAgICA8dGV4dCB4PSc1MCUnIHk9JzUwJScgZm9udC1mYW1pbHk9J01vbnRzZXJyYXQsIHNhbnMtc2VyaWYnIGZvbnQtc2l6ZT0nNjAnIGZpbGw9JyNmZmZmZmYnIHRleHQtYW5jaG9yPSdtaWRkbGUnIGRvbWluYW50LWJhc2VsaW5lPSdtaWRkbGUnIGZvbnQtd2VpZ2h0PSdib2xkJz4KICAgICAgICAgICAgICAgICAgICAgICAg0KLQstC10YDQtNGL0Lkg0YjQsNC80L/Rg9C90YwKICAgICAgICAgICAgICAgICAgICA8L3RleHQ+CiAgICAgICAgICAgICAgICA8L3N2Zz4=",
                            Name = "Твердый шампунь",
                            Price = 380m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Кристалл алунит. Без запаха.",
                            ImageUrl = "data:image/svg+xml;base64,CiAgICAgICAgICAgICAgICA8c3ZnIHdpZHRoPSc2MDAnIGhlaWdodD0nNDAwJyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPgogICAgICAgICAgICAgICAgICAgIDxyZWN0IHdpZHRoPScxMDAlJyBoZWlnaHQ9JzEwMCUnIGZpbGw9JyNmOGJiZDAnLz4KICAgICAgICAgICAgICAgICAgICA8dGV4dCB4PSc1MCUnIHk9JzUwJScgZm9udC1mYW1pbHk9J01vbnRzZXJyYXQsIHNhbnMtc2VyaWYnIGZvbnQtc2l6ZT0nNjAnIGZpbGw9JyMzMzMnIHRleHQtYW5jaG9yPSdtaWRkbGUnIGRvbWluYW50LWJhc2VsaW5lPSdtaWRkbGUnIGZvbnQtd2VpZ2h0PSdib2xkJz4KICAgICAgICAgICAgICAgICAgICAgICAg0JTQtdC30L7QtNC+0YDQsNC90YIKICAgICAgICAgICAgICAgICAgICA8L3RleHQ+CiAgICAgICAgICAgICAgICA8L3N2Zz4=",
                            Name = "Натуральный дезодорант",
                            Price = 550m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "100% растительный.",
                            ImageUrl = "data:image/svg+xml;base64,CiAgICAgICAgICAgICAgICA8c3ZnIHdpZHRoPSc2MDAnIGhlaWdodD0nNDAwJyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPgogICAgICAgICAgICAgICAgICAgIDxyZWN0IHdpZHRoPScxMDAlJyBoZWlnaHQ9JzEwMCUnIGZpbGw9JyMyNmE2OWEnLz4KICAgICAgICAgICAgICAgICAgICA8dGV4dCB4PSc1MCUnIHk9JzUwJScgZm9udC1mYW1pbHk9J01vbnRzZXJyYXQsIHNhbnMtc2VyaWYnIGZvbnQtc2l6ZT0nNjAnIGZpbGw9JyNmZmZmZmYnIHRleHQtYW5jaG9yPSdtaWRkbGUnIGRvbWluYW50LWJhc2VsaW5lPSdtaWRkbGUnIGZvbnQtd2VpZ2h0PSdib2xkJz4KICAgICAgICAgICAgICAgICAgICAgICAg0KHQv9C+0L3QtgogICAgICAgICAgICAgICAgICAgIDwvdGV4dD4KICAgICAgICAgICAgICAgIDwvc3ZnPg==",
                            Name = "Спонж Конняку",
                            Price = 300m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Прочный органический хлопок.",
                            ImageUrl = "data:image/svg+xml;base64,CiAgICAgICAgICAgICAgICA8c3ZnIHdpZHRoPSc2MDAnIGhlaWdodD0nNDAwJyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPgogICAgICAgICAgICAgICAgICAgIDxyZWN0IHdpZHRoPScxMDAlJyBoZWlnaHQ9JzEwMCUnIGZpbGw9JyNkN2NjYzgnLz4KICAgICAgICAgICAgICAgICAgICA8dGV4dCB4PSc1MCUnIHk9JzUwJScgZm9udC1mYW1pbHk9J01vbnRzZXJyYXQsIHNhbnMtc2VyaWYnIGZvbnQtc2l6ZT0nNjAnIGZpbGw9JyM1ZDQwMzcnIHRleHQtYW5jaG9yPSdtaWRkbGUnIGRvbWluYW50LWJhc2VsaW5lPSdtaWRkbGUnIGZvbnQtd2VpZ2h0PSdib2xkJz4KICAgICAgICAgICAgICAgICAgICAgICAg0K3QutC+LdGB0YPQvNC60LAKICAgICAgICAgICAgICAgICAgICA8L3RleHQ+CiAgICAgICAgICAgICAgICA8L3N2Zz4=",
                            Name = "Эко-сумка (Шоппер)",
                            Price = 500m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Стильная, держит тепло 2 часа.",
                            ImageUrl = "data:image/svg+xml;base64,CiAgICAgICAgICAgICAgICA8c3ZnIHdpZHRoPSc2MDAnIGhlaWdodD0nNDAwJyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPgogICAgICAgICAgICAgICAgICAgIDxyZWN0IHdpZHRoPScxMDAlJyBoZWlnaHQ9JzEwMCUnIGZpbGw9JyM0ZmMzZjcnLz4KICAgICAgICAgICAgICAgICAgICA8dGV4dCB4PSc1MCUnIHk9JzUwJScgZm9udC1mYW1pbHk9J01vbnRzZXJyYXQsIHNhbnMtc2VyaWYnIGZvbnQtc2l6ZT0nNjAnIGZpbGw9JyNmZmZmZmYnIHRleHQtYW5jaG9yPSdtaWRkbGUnIGRvbWluYW50LWJhc2VsaW5lPSdtaWRkbGUnIGZvbnQtd2VpZ2h0PSdib2xkJz4KICAgICAgICAgICAgICAgICAgICAgICAg0KLQtdGA0LzQvtC60YDRg9C20LrQsAogICAgICAgICAgICAgICAgICAgIDwvdGV4dD4KICAgICAgICAgICAgICAgIDwvc3ZnPg==",
                            Name = "Термокружка KeepCup",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Набор 4 шт + ершик.",
                            ImageUrl = "data:image/svg+xml;base64,CiAgICAgICAgICAgICAgICA8c3ZnIHdpZHRoPSc2MDAnIGhlaWdodD0nNDAwJyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPgogICAgICAgICAgICAgICAgICAgIDxyZWN0IHdpZHRoPScxMDAlJyBoZWlnaHQ9JzEwMCUnIGZpbGw9JyNjZmQ4ZGMnLz4KICAgICAgICAgICAgICAgICAgICA8dGV4dCB4PSc1MCUnIHk9JzUwJScgZm9udC1mYW1pbHk9J01vbnRzZXJyYXQsIHNhbnMtc2VyaWYnIGZvbnQtc2l6ZT0nNjAnIGZpbGw9JyM0NTVhNjQnIHRleHQtYW5jaG9yPSdtaWRkbGUnIGRvbWluYW50LWJhc2VsaW5lPSdtaWRkbGUnIGZvbnQtd2VpZ2h0PSdib2xkJz4KICAgICAgICAgICAgICAgICAgICAgICAg0KLRgNGD0LHQvtGH0LrQuAogICAgICAgICAgICAgICAgICAgIDwvdGV4dD4KICAgICAgICAgICAgICAgIDwvc3ZnPg==",
                            Name = "Металлические трубочки",
                            Price = 600m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Замена пищевой пленке.",
                            ImageUrl = "data:image/svg+xml;base64,CiAgICAgICAgICAgICAgICA8c3ZnIHdpZHRoPSc2MDAnIGhlaWdodD0nNDAwJyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPgogICAgICAgICAgICAgICAgICAgIDxyZWN0IHdpZHRoPScxMDAlJyBoZWlnaHQ9JzEwMCUnIGZpbGw9JyNmZmVjYjMnLz4KICAgICAgICAgICAgICAgICAgICA8dGV4dCB4PSc1MCUnIHk9JzUwJScgZm9udC1mYW1pbHk9J01vbnRzZXJyYXQsIHNhbnMtc2VyaWYnIGZvbnQtc2l6ZT0nNjAnIGZpbGw9JyNmZjZmMDAnIHRleHQtYW5jaG9yPSdtaWRkbGUnIGRvbWluYW50LWJhc2VsaW5lPSdtaWRkbGUnIGZvbnQtd2VpZ2h0PSdib2xkJz4KICAgICAgICAgICAgICAgICAgICAgICAg0KHQsNC70YTQtdGC0LrQuAogICAgICAgICAgICAgICAgICAgIDwvdGV4dD4KICAgICAgICAgICAgICAgIDwvc3ZnPg==",
                            Name = "Восковые салфетки",
                            Price = 800m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Запеченные мюсли с орехами.",
                            ImageUrl = "data:image/svg+xml;base64,CiAgICAgICAgICAgICAgICA8c3ZnIHdpZHRoPSc2MDAnIGhlaWdodD0nNDAwJyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPgogICAgICAgICAgICAgICAgICAgIDxyZWN0IHdpZHRoPScxMDAlJyBoZWlnaHQ9JzEwMCUnIGZpbGw9JyNmZmNjODAnLz4KICAgICAgICAgICAgICAgICAgICA8dGV4dCB4PSc1MCUnIHk9JzUwJScgZm9udC1mYW1pbHk9J01vbnRzZXJyYXQsIHNhbnMtc2VyaWYnIGZvbnQtc2l6ZT0nNjAnIGZpbGw9JyNlNjUxMDAnIHRleHQtYW5jaG9yPSdtaWRkbGUnIGRvbWluYW50LWJhc2VsaW5lPSdtaWRkbGUnIGZvbnQtd2VpZ2h0PSdib2xkJz4KICAgICAgICAgICAgICAgICAgICAgICAg0JPRgNCw0L3QvtC70LAKICAgICAgICAgICAgICAgICAgICA8L3RleHQ+CiAgICAgICAgICAgICAgICA8L3N2Zz4=",
                            Name = "Гранола домашняя",
                            Price = 450m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Японский зеленый чай.",
                            ImageUrl = "data:image/svg+xml;base64,CiAgICAgICAgICAgICAgICA8c3ZnIHdpZHRoPSc2MDAnIGhlaWdodD0nNDAwJyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPgogICAgICAgICAgICAgICAgICAgIDxyZWN0IHdpZHRoPScxMDAlJyBoZWlnaHQ9JzEwMCUnIGZpbGw9JyM2NmJiNmEnLz4KICAgICAgICAgICAgICAgICAgICA8dGV4dCB4PSc1MCUnIHk9JzUwJScgZm9udC1mYW1pbHk9J01vbnRzZXJyYXQsIHNhbnMtc2VyaWYnIGZvbnQtc2l6ZT0nNjAnIGZpbGw9JyNmZmZmZmYnIHRleHQtYW5jaG9yPSdtaWRkbGUnIGRvbWluYW50LWJhc2VsaW5lPSdtaWRkbGUnIGZvbnQtd2VpZ2h0PSdib2xkJz4KICAgICAgICAgICAgICAgICAgICAgICAg0JzQsNGC0YfQsAogICAgICAgICAgICAgICAgICAgIDwvdGV4dD4KICAgICAgICAgICAgICAgIDwvc3ZnPg==",
                            Name = "Чай Матча (Matcha)",
                            Price = 990m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Extra Virgin.",
                            ImageUrl = "data:image/svg+xml;base64,CiAgICAgICAgICAgICAgICA8c3ZnIHdpZHRoPSc2MDAnIGhlaWdodD0nNDAwJyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPgogICAgICAgICAgICAgICAgICAgIDxyZWN0IHdpZHRoPScxMDAlJyBoZWlnaHQ9JzEwMCUnIGZpbGw9JyNmZmZmZmYnLz4KICAgICAgICAgICAgICAgICAgICA8dGV4dCB4PSc1MCUnIHk9JzUwJScgZm9udC1mYW1pbHk9J01vbnRzZXJyYXQsIHNhbnMtc2VyaWYnIGZvbnQtc2l6ZT0nNjAnIGZpbGw9JyMzMzMnIHRleHQtYW5jaG9yPSdtaWRkbGUnIGRvbWluYW50LWJhc2VsaW5lPSdtaWRkbGUnIGZvbnQtd2VpZ2h0PSdib2xkJz4KICAgICAgICAgICAgICAgICAgICAgICAg0JzQsNGB0LvQvgogICAgICAgICAgICAgICAgICAgIDwvdGV4dD4KICAgICAgICAgICAgICAgIDwvc3ZnPg==",
                            Name = "Кокосовое масло",
                            Price = 700m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Нейлоновый мешочек.",
                            ImageUrl = "data:image/svg+xml;base64,CiAgICAgICAgICAgICAgICA8c3ZnIHdpZHRoPSc2MDAnIGhlaWdodD0nNDAwJyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnPgogICAgICAgICAgICAgICAgICAgIDxyZWN0IHdpZHRoPScxMDAlJyBoZWlnaHQ9JzEwMCUnIGZpbGw9JyNlMGUwZTAnLz4KICAgICAgICAgICAgICAgICAgICA8dGV4dCB4PSc1MCUnIHk9JzUwJScgZm9udC1mYW1pbHk9J01vbnRzZXJyYXQsIHNhbnMtc2VyaWYnIGZvbnQtc2l6ZT0nNjAnIGZpbGw9JyMzMzMnIHRleHQtYW5jaG9yPSdtaWRkbGUnIGRvbWluYW50LWJhc2VsaW5lPSdtaWRkbGUnIGZvbnQtd2VpZ2h0PSdib2xkJz4KICAgICAgICAgICAgICAgICAgICAgICAg0JzQtdGI0L7Rh9C10LoKICAgICAgICAgICAgICAgICAgICA8L3RleHQ+CiAgICAgICAgICAgICAgICA8L3N2Zz4=",
                            Name = "Мешочек для молока",
                            Price = 350m
                        });
                });

            modelBuilder.Entity("EcoShop.Models.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EcoShop.Models.OrderItem", b =>
                {
                    b.HasOne("EcoShop.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("EcoShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EcoShop.Models.ProductReview", b =>
                {
                    b.HasOne("EcoShop.Models.Product", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoShop.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EcoShop.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
