// <auto-generated />
using System;
using EcoShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251214110215_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("EcoShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Дом и быт"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Красота и уход"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Здоровое питание"
                        });
                });

            modelBuilder.Entity("EcoShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EcoShop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EcoShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            Description = "100% биоразлагаемая ручка. Угольное напыление.",
                            ImageUrl = "https://placehold.co/600x400/81c784/ffffff?text=Бамбуковая+щетка",
                            Name = "Бамбуковая зубная щетка",
                            Price = 250m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Экономичный и натуральный. Хватает на 3 месяца.",
                            ImageUrl = "https://placehold.co/600x400/ba68c8/ffffff?text=Твердый+шампунь",
                            Name = "Твердый шампунь",
                            Price = 380m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Кристалл алунит. Без запаха и пятен.",
                            ImageUrl = "https://placehold.co/600x400/f8bbd0/ffffff?text=Дезодорант",
                            Name = "Натуральный дезодорант",
                            Price = 550m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Для мягкого очищения лица. 100% растительный.",
                            ImageUrl = "https://placehold.co/600x400/26a69a/ffffff?text=Спонж",
                            Name = "Спонж Конняку",
                            Price = 300m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Прочный органический хлопок. Выдерживает 15 кг.",
                            ImageUrl = "https://placehold.co/600x400/d7ccc8/5d4037?text=Эко-сумка",
                            Name = "Эко-сумка (Шоппер)",
                            Price = 500m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Стильная, держит тепло 2 часа. Стекло и пробка.",
                            ImageUrl = "https://placehold.co/600x400/4fc3f7/ffffff?text=Термокружка",
                            Name = "Термокружка KeepCup",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Description = "Набор 4 шт + ершик. Нержавеющая сталь.",
                            ImageUrl = "https://placehold.co/600x400/cfd8dc/455a64?text=Трубочки",
                            Name = "Металлические трубочки",
                            Price = 600m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Description = "Замена пищевой пленке. Хлопок + пчелиный воск.",
                            ImageUrl = "https://placehold.co/600x400/ffecb3/ff6f00?text=Салфетки",
                            Name = "Восковые салфетки",
                            Price = 800m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Description = "Запеченные мюсли с орехами и медом. Без сахара.",
                            ImageUrl = "https://placehold.co/600x400/ffcc80/e65100?text=Гранола",
                            Name = "Гранола домашняя",
                            Price = 450m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            Description = "Японский зеленый чай высшего сорта. Бодрит.",
                            ImageUrl = "https://placehold.co/600x400/66bb6a/ffffff?text=Матча",
                            Name = "Чай Матча (Matcha)",
                            Price = 990m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Extra Virgin. Для жарки и косметических целей.",
                            ImageUrl = "https://placehold.co/600x400/ffffff/333333?text=Масло",
                            Name = "Кокосовое масло",
                            Price = 700m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Нейлоновый мешочек для фильтрации молока.",
                            ImageUrl = "https://placehold.co/600x400/e0e0e0/333333?text=Мешочек",
                            Name = "Мешочек для орехового молока",
                            Price = 350m
                        });
                });

            modelBuilder.Entity("EcoShop.Models.ProductReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("EcoShop.Models.OrderItem", b =>
                {
                    b.HasOne("EcoShop.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("EcoShop.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EcoShop.Models.ProductReview", b =>
                {
                    b.HasOne("EcoShop.Models.Product", null)
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EcoShop.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("EcoShop.Models.Product", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
